### ISSUE TITLE
Build for Linux

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [marius-m/wt4#2]
How could I build the Linux release?
As for now I'm getting 
`assert deployPropertyFile.exists()` after
`gradle build` command

**Comment by marius-m** [comment]
There are some files that are not included in the build (like in this case a credentials file) 

Your issue should fix with: 
- Add file deploy.properties to root project file (ex.: ~/Projects/wt4/deploy.properties)
- Add test properties (add to file)

```
ga=test
remote_user=test
remote_pass=test
```

I'll try to make a build tomorrow to see what issues arise. 

On what distribution you're trying to build ?

**Comment by Ilya-Kuchaev** [comment]
Ubuntu 16.04

**Comment by marius-m** [comment]
Ok ill try to take a look in upcoming evenings

**Comment by marius-m** [comment]
Hm okay first try didn't go out very well. I've managed to compile and pack it into *.deb, but after extraction there seems to be two problems to work properly. 
- Need custom postscript to change permissions to the user one after extraction of the deb.
- Need to figure out how to bind a shortcut executor to run the app. 

The good part that app seems to work properly after these issues are solved. I'll try to dig a bit further later on.

**Comment by marius-m** [comment]
Finally, with a couple of bumps, i've finished bundling properly for linux (more like debian distro). Had a couple of problems setting proper permissions, getting runtime correctly, but postscript installation fixed it. 

Keep in mind that app has a dependency for `java8`, so `$JAVA_HOME` should be set properly, or at least `java -version` should return a jre. Otherwise you will probably need a `fat` archive for the app to work. 

As much as i've tested it worked correctly, though more extensive use will say more. 
- [Small package installer](https://dl.dropboxusercontent.com/u/60630588/linux/wt4-4.0.deb)
- [Fat package installer](https://dl.dropboxusercontent.com/u/60630588/linux/wt4-4.0_fat.deb)

**Comment by Ilya-Kuchaev** [comment]
Installer produces an error:
```
➜  Downloads sudo dpkg -i wt4-4.0_fat.deb 
(Reading database ... 280571 files and directories currently installed.)
Preparing to unpack wt4-4.0_fat.deb ...
Removing shortcut
Unpacking wt4 (4.0) over (4.0) ...
Setting up wt4 (4.0) ...
Adding shortcut to the menu
Adding permissions for update folder
chmod: cannot access '/opt/WT4/app': No such file or directory
dpkg: error processing package wt4 (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 wt4
➜  Downloads sudo mkdir /opt/WT4/app
➜  Downloads sudo apt -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-31 linux-headers-4.4.0-31-generic
  linux-image-4.4.0-31-generic linux-image-extra-4.4.0-31-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up wt4 (4.0) ...
Adding shortcut to the menu
Adding permissions for update folder
Using bundled JRE
```
Application doesn't start from the Desktop icon. If I try to start it from the command line:
```
➜  Downloads cd /opt/WT4 
➜  WT4 ./WT4 
WT4 No main class specified
WT4 Failed to launch JVM
```
Ther is no syslog entries.

**Comment by marius-m** [comment]
Thanks for the report.

Hm, seems like there are a few problems here, 
- I've used hardcoded paths for changing permissions (location does not seem to be at "/opt/WT4")
- Fails to target correct location of the runtime environment (probably due to location changes)

I was probably to naive, that hardcoded locations will work. I'll try to fix this.

**Comment by marius-m** [comment]
Okay, I'm not sure but the install process should be more smooth right now. 
Also its very weird that when unpackaging, the packager did not generate needed folders, and when tinkering around i've managed to recreate your situation. 

**Solution:**
- Redownload [Fat package installer](https://dl.dropboxusercontent.com/u/60630588/linux/wt4-4.0_fat.deb)
- Run these commands: `sudo dpkg -r wt4 && sudo dpkg -i wt4-4.0_fat.deb` 

This should will reinstall package. 

**Troubleshooting**
If this will not work, please run a few commands and post outputs here for more information: 
- Output of the installer when running `sudo dpkg -i wt...deb`
- `ls -la /opt` - file list where package should be extracted
- `ls- la /opt/WT4`
- `ls -la /opt/WT4/app`
- `cat /opt/WT4/app/WT4.cfg`
- `echo $JAVA_HOME`

Thanks!
