### ISSUE TITLE
App shuts down after loading 99% on macOS Sierra

### ISSUE THREAD

**Issue by mustafaturabsalesforce** [marius-m/wt4#7]
Hi,

Thanks for all the effort in developing this wonderful add on. I tried to open it on my macbook with macOS Sierra. It opens up and shortly after auto shuts down. Any idea how can I resolve this? I have Java 8 update 121 installed.

Thanks,
Mustafa

**Comment by marius-m** [comment]
Hi, can you please try opening terminal and paste in this command: `cat /Applications/WT4.app/Contents/Java/app/launcher.log | pbcopy` . This will copy a log, what is the problem when launching. Paste it here, and we'll go from there.

**Comment by dinusuresh** [comment]
Facing the same issue on ubuntu 16.04 (ElementaryOS - 0.4 Loki)

**Comment by marius-m** [comment]
Ill try it out today in the evening.

**Comment by marius-m** [comment]
Ok i've tried running some tests. I've tried two macOS (tho' both on Sierra) and did not run into any problems. 

I've tried running linux version, though i've bumped into some problems, i've managed to run it (Event though was stuck on some debian version). 

So my suggestion would be this: 
1. Whenever installing, try the "fat" version, because it bundles java jre together and does not run into problems when trying to find it.
2. You can try re-downloading the app package. 
2.1 On linux: In terminal type: `rm /opt/WT4/app/app/app.jar && rm /opt/WT4/app/app/digest.txt`. 
2.2 On mac: In terminal type `rm /Applications/WT4.app/Contents/Java/app/app.jar && rm /Applications/WT4.app/Contents/Java/app/digest.txt`
3. For me to find what is wrong, please provide more info. Paste it here.
3.1 On linux type: `cat /opt/WT4/app/app/launcher.log`
3.2 On mac type: `cat /Applications/WT4.app/Contents/Java/app/launcher.log`

Tomorrow ill try on elementary os, maybe that will give some insight. 
Thanks for trying :)

**Comment by dinusuresh** [comment]
I got it running after running: `sudo apt-get install openjdk-8-jre openjfx`

I guess the openjfx was the problem. I did not have it installed on the system.

All is good now. Thanks :+1:

**Comment by marius-m** [comment]
Oh cool, thanks for sharing the solution! 🎉
